```
.
└── hbnb
    ├── README.md
    ├── app
    │   ├── __init__.py
    │   ├── api
    │   │   ├── __init__.py
    │   │   └── v1
    │   │       ├── __init__.py
    │   │       ├── admin.py
    │   │       ├── amenities.py
    │   │       ├── auth.py
    │   │       ├── place.py
    │   │       ├── review.py
    │   │       └── users.py
    │   ├── extends.py
    │   ├── models
    │   │   ├── __init__.py
    │   │   ├── amenities.py
    │   │   ├── baseModel.py
    │   │   ├── place.py
    │   │   ├── review.py
    │   │   └── users.py
    │   ├── persistence
    │   │   ├── __init__.py
    │   │   └── repository.py
    │   ├── services
    │   │   ├── __init__.py
    │   │   └── facade.py
    │   ├── test_models
    │   │   ├── test_all_models.py
    │   │   ├── test_amenity.py
    │   │   ├── test_place.py
    │   │   ├── test_review.py
    │   │   └── test_user.py
    │   └── tests
    │       ├── test_amenity.py
    │       ├── test_place.py
    │       ├── test_review.py
    │       └── test_user.py
    ├── config.py
    ├── extensions.py
    ├── instance
    │   └── development.db
    ├── requirements.txt
    ├── run.py
    └── sql
        ├── crud.sql
        ├── initial_datas.sql
        ├── passwd_hasher.py
        ├── tables_creation.sql
        └── uuid_generator.py
```
